# Generated by Django 4.1.7 on 2026-02-01 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('run', 'Running'), ('walk', 'Walking'), ('cycling', 'Cycling'), ('gym', 'Gym')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='💪', max_length=50)),
                ('default_calories_multiplier', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name_plural': 'Workout Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('workout_type', models.CharField(choices=[('run', 'Running'), ('walk', 'Walking'), ('cycling', 'Cycling'), ('gym', 'Gym')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('distance', models.FloatField(help_text='Distance in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('calories', models.PositiveIntegerField(help_text='Calories burned', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance_7days', models.FloatField(default=0.0)),
                ('total_time_7days', models.PositiveIntegerField(default=0)),
                ('workouts_count_7days', models.PositiveIntegerField(default=0)),
                ('total_distance_30days', models.FloatField(default=0.0)),
                ('total_time_30days', models.PositiveIntegerField(default=0)),
                ('workouts_count_30days', models.PositiveIntegerField(default=0)),
                ('total_distance_alltime', models.FloatField(default=0.0)),
                ('total_time_alltime', models.PositiveIntegerField(default=0)),
                ('workouts_count_alltime', models.PositiveIntegerField(default=0)),
                ('total_calories_alltime', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', '-date'], name='workouts_wo_user_id_f4b7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'workout_type'], name='workouts_wo_user_id_23c1bb_idx'),
        ),
    ]
